services:
  web:
    container_name: site-designativa_site-designa
    image: node:18-alpine
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm start"
    volumes:
      - .:/app
